// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3617.Eugene;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.Victor;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS



/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private Victor victor0 = new Victor(0);
	private Victor victor1 = new Victor(1);
	private Victor victor2 = new Victor(2);
	private Victor victor3 = new Victor(3);
	
	private Spark spark4 = new Spark(4);
	private Spark spark5 = new Spark(4);
	private Spark spark6 = new Spark(4);
	private Spark spark7 = new Spark(4);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Victor getVictor0() {
		return victor0;
	}

	public Victor getVictor1() {
		return victor1;
	}

	public Victor getVictor2() {
		return victor2;
	}

	public Victor getVictor3() {
		return victor3;
	}

	public Spark getSpark4() {
		return spark4;
	}

	public Spark getSpark5() {
		return spark5;
	}

	public Spark getSpark6() {
		return spark6;
	}

	public Spark getSpark7() {
		return spark7;
	}

	public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
