// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3617.Eugene.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3617.Eugene.Robot;

/**
 *
 */
public class Driver extends Command {
	
	private double x;
	private double y;
	private double stickY;
	private double stickX;
    public Driver() {

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	x = 0;
    	y = 0;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	stickY = Robot.oi.getLeftStick().getY();
    	stickX = Robot.oi.getLeftStick().getX();
    	//arm tilt code
    	Robot.robotMap.getSpark5().set(Robot.oi.getRightStick().getY());
    	
    	//claw grab/release
    	if(Robot.oi.getRightTrig().get())
    		Robot.robotMap.getVictor3().set(0.8);
    	else if(Robot.oi.getRightThumb().get())
    		Robot.robotMap.getVictor3().set(-0.8);
    	else
    		Robot.robotMap.getVictor3().set(0);
    	
    	//arm extend
    	if(Robot.oi.getRight3().get())
    		Robot.robotMap.getSpark4().set(-0.6);
    	else if(Robot.oi.getRight4().get())
    		Robot.robotMap.getSpark4().set(0.3);
    	else
    		Robot.robotMap.getSpark4().set(0);
    	//y Stepper
    	if((y > 0 && stickY < y) || (y < 0 && stickY > y))
    	{
    		y = stickY;
    	}
    	else if(stickY < -0.1  && y > stickY)
    	{
    		y -= 0.2;
    	}
    	else if(stickY > 0.1  && y < stickY)
    	{
    		y += 0.2;
    	}
    	//x Stepper
    	if((x > 0 && stickX < x) || (x < 0 && stickX > x))
    	{
    		x = stickX;
    	}
    	else if(stickX < -0.1  && x > stickX)
    	{
    		x -= 0.2;
    	}
    	else if(stickX > 0.1  && x < stickX)
    	{
    		x += 0.2;
    	}
    	//actual driving
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {

    	Robot.robotMap.getSpark5().set(0);
		Robot.robotMap.getVictor3().set(0);
		Robot.robotMap.getSpark4().set(0);
    }
}
